name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  # -------------------------------------------
  # Job 1: Build and Push Docker Images
  # -------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, catalog-service, orders-service, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push ${{ matrix.service }}
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PREFIX: ${{ secrets.ECR_REPOSITORY_PREFIX }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
           IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY_PREFIX/${{ matrix.service }}:$IMAGE_TAG"
           docker build -t "$IMAGE_URI" ./${{ matrix.service }}
           docker push "$IMAGE_URI"

  # -------------------------------------------
  # Job 2: Deploy
  # -------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Get Server public IP address by Tag
        run: |
          EC2_HOST=$(aws ec2 describe-instances \
          --region ${{ secrets.AWS_REGION }} \
          --filters "Name=tag:Name,Values=meridian-retail-server" "Name=instance-state-name,Values=running" \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
          echo "EC2_HOST=$EC2_HOST" >> $GITHUB_ENV

      - name: Copy scripts to EC2 Instance
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./scripts/*"
          target: "/home/${{ secrets.EC2_USERNAME }}/app"

      - name: Copy Nginx folder to EC2 Instance
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./nginx/*"
          target: "/home/${{ secrets.EC2_USERNAME }}/app"

      - name: Copy docker compose file to EC2 Instance
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/${{ secrets.EC2_USERNAME }}/app"
          
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
           
            cd /home/${{ secrets.EC2_USERNAME }}/app || exit 1
            # Create .env
            cat << 'EOF' > .env
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRY_MINUTES=${{ secrets.JWT_EXPIRY_MINUTES }}
            DOMAIN=${{ secrets.DOMAIN }}
            ECR_REPOSITORY_PREFIXT=${{ secrets.ECR_REPOSITORY_PREFIX }}
            EOF
            chmod 600 .env

            chmod +x docker-compose.prod.yml
            
            cd /home/${{ secrets.EC2_USERNAME }}/app/scripts
            
            chmod +x *.sh

            ./server_setup.sh

            cd ..

            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            
            docker compose pull

            docker compose up -d --remove-orphans

            cd /home/${{ secrets.EC2_USERNAME }}/app/nginx

            sudo cp meridian-http.conf /etc/nginx/sites-available/meridian.conf

            cd ..

            sudo ln -s /etc/nginx/sites-available/meridian-app /etc/nginx/sites-enabled/

            sudo rm /etc/nginx/sites-enabled/default

            sudo nginx -t

            sudo systemctl reload nginx

            sudo certbot renew --dry-run
     
                
          
          

      
          
        


    
