name: CI/CD Workflow

on:
  workflow_dispatch: {}


jobs:
  # -------------------------------------------
  # Job 1: Build and Push Docker Images
  # -------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        include:
          - folder: auth-service
            repo: auth-repo
          - folder: catalog-service
            repo: catalog-repo
          - folder: orders-service
            repo: orders-repo
          - folder: frontend
            repo: frontend-repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push ${{ matrix.repo }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
           IMAGE_URI="$ECR_REGISTRY/${{ matrix.repo }}:$IMAGE_TAG"
           docker build -t "$IMAGE_URI" ./${{ matrix.folder }}
           docker push "$IMAGE_URI"

  # -------------------------------------------
  # Job 2: Deploy
  # -------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Get Server public IP address by Tag
        run: |
          EC2_INSTANCE=$(aws ec2 describe-instances \
          --region ${{ secrets.AWS_REGION }} \
          --filters "Name=tag:Name,Values=meridian-retail-server" "Name=instance-state-name,Values=running" \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
          if [ -z "$EC2_INSTANCE" ] || [ "$EC2_INSTANCE" == None ]; then
            echo "No running instance found with tag Name=meridian-retail-server"
            exit 1
          fi
          echo "EC2_INSTANCE=$EC2_INSTANCE" >> $GITHUB_ENV

      - name: Get Security Group ID
        run: |
          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
          --region ${{ secrets.AWS_REGION }} \
          --filters "Name=tag:Name,Values=meridian-retail-server-sg-sg" \
          --query 'SecurityGroups[0].GroupId' \
          --output text)

          if [ -z "$SECURITY_GROUP_ID" ] || [ "$SECURITY_GROUP_ID" = "None" ]; then
            echo "Security group not found"
            exit 1
          fi

          echo "Security Group ID: $SECURITY_GROUP_ID"
          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> "$GITHUB_ENV"

      - name: Get GitHub runner IP
        id: runner-ip
        run: |
          echo "ip=$(curl -s https://ipv4.icanhazip.com)" >> "$GITHUB_OUTPUT"

      - name: Allow GitHub runner SSH
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ env.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.runner-ip.outputs.ip }}/32

      - name: Copy docker compose file to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.EC2_INSTANCE }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/${{ secrets.EC2_USERNAME }}/app"
          
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_INSTANCE }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ECR_REGISTRY
          script: |
            set -e
            cd /home/${{ secrets.EC2_USERNAME }}/app || exit 1
            # Create .env
            cat << EOF > .env
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRY_MINUTES=${{ secrets.JWT_EXPIRY_MINUTES }}
            DOMAIN=${{ secrets.DOMAIN }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            ECR_REGISTRY=${ECR_REGISTRY}
            IMAGE_TAG=${{ github.sha }}
            EOF
            chmod 600 .env

            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin "$ECR_REGISTRY"
            
            docker compose -f docker-compose.prod.yml pull

            docker compose -f docker-compose.prod.yml up -d --remove-orphans
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      
      - name: Remove GitHub runner SSH access
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id ${{ env.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.runner-ip.outputs.ip }}/32

